version: '3'
services: 
  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile.nginx
    depends_on: 
      - rotator
    environment:
      DOMAIN_NAME: "localhost"
    ports:
      - "80:80"
      - "443:443"
    links:
      - rotator
    restart: always

  rotator:
    build: 
      context: ./
      dockerfile: Dockerfile.python
