apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: rotator
  name: rotator
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rotator
    spec:
      containers:
      - image: rotator
        name: rotator
        resources: {}
        volumeMounts:
        - mountPath: /tmp/rotator
          name: rotator-claim0
      restartPolicy: Always
      volumes:
      - name: rotator-claim0
        persistentVolumeClaim:
          claimName: rotator-claim0
status: {}
